// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  agentId: __t.string().primaryKey().name("agent_id"),
  agentType: __t.string().name("agent_type"),
  x: __t.f64(),
  z: __t.f64(),
  targetX: __t.f64().name("target_x"),
  targetZ: __t.f64().name("target_z"),
  speed: __t.f64(),
  state: __t.string(),
  color: __t.string(),
  spawnedAt: __t.i64().name("spawned_at"),
});
