// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  editId: __t.string().primaryKey().name("edit_id"),
  editType: __t.string().name("edit_type"),
  fromX: __t.i32().name("from_x"),
  fromZ: __t.i32().name("from_z"),
  fromHeight: __t.i32().name("from_height"),
  toX: __t.i32().name("to_x"),
  toZ: __t.i32().name("to_z"),
  voxelType: __t.i32().name("voxel_type"),
  height: __t.i32(),
  label: __t.string(),
  placedBy: __t.string().name("placed_by"),
  color: __t.string(),
  createdAt: __t.i64().name("created_at"),
});
