// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.i32().primaryKey(),
  population: __t.i32(),
  happiness: __t.f64(),
  economyScore: __t.f64().name("economy_score"),
  healthScore: __t.f64().name("health_score"),
  trafficScore: __t.f64().name("traffic_score"),
  greenScore: __t.f64().name("green_score"),
  disasterActive: __t.string().name("disaster_active"),
  disasterIntensity: __t.i32().name("disaster_intensity"),
  populationLoss: __t.i32().name("population_loss"),
  lastUpdated: __t.i64().name("last_updated"),
});
