// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  eventId: __t.string().primaryKey().name("event_id"),
  eventType: __t.string().name("event_type"),
  triggeredBy: __t.string().name("triggered_by"),
  intensity: __t.i32(),
  affectedX: __t.i32().name("affected_x"),
  affectedZ: __t.i32().name("affected_z"),
  radius: __t.i32(),
  duration: __t.i32(),
  label: __t.string(),
  createdAt: __t.i64().name("created_at"),
});
