// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  bulletinId: __t.string().primaryKey().name("bulletin_id"),
  headlineText: __t.string().name("headline_text"),
  bodyText: __t.string().name("body_text"),
  disasterType: __t.string().name("disaster_type"),
  triggeredBy: __t.string().name("triggered_by"),
  createdAt: __t.i64().name("created_at"),
});
