// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.string().primaryKey(),
  username: __t.string(),
  cursorX: __t.i32().name("cursor_x"),
  cursorZ: __t.i32().name("cursor_z"),
  color: __t.string(),
  isOnline: __t.bool().name("is_online"),
  score: __t.i32(),
  lastSeen: __t.i64().name("last_seen"),
  isPlacingDisaster: __t.bool().name("is_placing_disaster"),
  disasterPreviewX: __t.i32().name("disaster_preview_x"),
  disasterPreviewZ: __t.i32().name("disaster_preview_z"),
  disasterPreviewRadius: __t.i32().name("disaster_preview_radius"),
  lastAction: __t.string().name("last_action"),
  lastActionAt: __t.i64().name("last_action_at"),
});
