// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  offerId: __t.string().primaryKey().name("offer_id"),
  fromPlayer: __t.string().name("from_player"),
  toPlayer: __t.string().name("to_player"),
  offerType: __t.string().name("offer_type"),
  offerDetails: __t.string().name("offer_details"),
  status: __t.string(),
  createdAt: __t.i64().name("created_at"),
});
