// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Agent = __t.object("Agent", {
  agentId: __t.string(),
  agentType: __t.string(),
  x: __t.f64(),
  z: __t.f64(),
  targetX: __t.f64(),
  targetZ: __t.f64(),
  speed: __t.f64(),
  state: __t.string(),
  color: __t.string(),
  spawnedAt: __t.i64(),
});
export type Agent = __Infer<typeof Agent>;

export const BuildingMeta = __t.object("BuildingMeta", {
  buildingId: __t.string(),
  description: __t.string(),
  gdpContributionUsd: __t.f64(),
  placedAt: __t.i64(),
});
export type BuildingMeta = __Infer<typeof BuildingMeta>;

export const CityEdit = __t.object("CityEdit", {
  editId: __t.string(),
  editType: __t.string(),
  fromX: __t.i32(),
  fromZ: __t.i32(),
  fromHeight: __t.i32(),
  toX: __t.i32(),
  toZ: __t.i32(),
  voxelType: __t.i32(),
  height: __t.i32(),
  label: __t.string(),
  placedBy: __t.string(),
  color: __t.string(),
  createdAt: __t.i64(),
});
export type CityEdit = __Infer<typeof CityEdit>;

export const CityStats = __t.object("CityStats", {
  id: __t.i32(),
  population: __t.i32(),
  happiness: __t.f64(),
  economyScore: __t.f64(),
  healthScore: __t.f64(),
  trafficScore: __t.f64(),
  greenScore: __t.f64(),
  disasterActive: __t.string(),
  disasterIntensity: __t.i32(),
  populationLoss: __t.i32(),
  lastUpdated: __t.i64(),
});
export type CityStats = __Infer<typeof CityStats>;

export const EconomicData = __t.object("EconomicData", {
  id: __t.i32(),
  gdpGrowth: __t.f64(),
  inflation: __t.f64(),
  unemployment: __t.f64(),
  country: __t.string(),
  updatedAt: __t.i64(),
});
export type EconomicData = __Infer<typeof EconomicData>;

export const Event = __t.object("Event", {
  eventId: __t.string(),
  eventType: __t.string(),
  triggeredBy: __t.string(),
  intensity: __t.i32(),
  affectedX: __t.i32(),
  affectedZ: __t.i32(),
  radius: __t.i32(),
  duration: __t.i32(),
  label: __t.string(),
  createdAt: __t.i64(),
});
export type Event = __Infer<typeof Event>;

export const NewsBulletin = __t.object("NewsBulletin", {
  bulletinId: __t.string(),
  headlineText: __t.string(),
  bodyText: __t.string(),
  disasterType: __t.string(),
  triggeredBy: __t.string(),
  createdAt: __t.i64(),
});
export type NewsBulletin = __Infer<typeof NewsBulletin>;

export const Player = __t.object("Player", {
  identity: __t.string(),
  username: __t.string(),
  cursorX: __t.i32(),
  cursorZ: __t.i32(),
  color: __t.string(),
  isOnline: __t.bool(),
  score: __t.i32(),
  lastSeen: __t.i64(),
  isPlacingDisaster: __t.bool(),
  disasterPreviewX: __t.i32(),
  disasterPreviewZ: __t.i32(),
  disasterPreviewRadius: __t.i32(),
  lastAction: __t.string(),
  lastActionAt: __t.i64(),
});
export type Player = __Infer<typeof Player>;

export const SimulationClock = __t.object("SimulationClock", {
  id: __t.i32(),
  currentTick: __t.i64(),
  speedMultiplier: __t.f64(),
  isPaused: __t.bool(),
  simulatedYear: __t.i32(),
});
export type SimulationClock = __Infer<typeof SimulationClock>;

export const SurfaceGrid = __t.object("SurfaceGrid", {
  id: __t.i32(),
  width: __t.i32(),
  depth: __t.i32(),
  gridData: __t.string(),
});
export type SurfaceGrid = __Infer<typeof SurfaceGrid>;

export const TradeOffer = __t.object("TradeOffer", {
  offerId: __t.string(),
  fromPlayer: __t.string(),
  toPlayer: __t.string(),
  offerType: __t.string(),
  offerDetails: __t.string(),
  status: __t.string(),
  createdAt: __t.i64(),
});
export type TradeOffer = __Infer<typeof TradeOffer>;

export const WeatherState = __t.object("WeatherState", {
  id: __t.i32(),
  city: __t.string(),
  tempC: __t.f64(),
  weatherCode: __t.i32(),
  windSpeed: __t.f64(),
  precipitation: __t.f64(),
  updatedAt: __t.i64(),
});
export type WeatherState = __Infer<typeof WeatherState>;

