// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddScoreReducer from "../add_score_reducer";
import ChangeZoneReducer from "../change_zone_reducer";
import ClearDisasterReducer from "../clear_disaster_reducer";
import CreateTradeOfferReducer from "../create_trade_offer_reducer";
import JoinCityReducer from "../join_city_reducer";
import LeaveCityReducer from "../leave_city_reducer";
import MoveBuildingReducer from "../move_building_reducer";
import MoveCursorReducer from "../move_cursor_reducer";
import PlaceBuildingReducer from "../place_building_reducer";
import RemoveBuildingReducer from "../remove_building_reducer";
import ResetCityReducer from "../reset_city_reducer";
import RespondToTradeReducer from "../respond_to_trade_reducer";
import TriggerDisasterReducer from "../trigger_disaster_reducer";
import UndoLastEditReducer from "../undo_last_edit_reducer";
import UpdateCityStatsReducer from "../update_city_stats_reducer";
import UpdateEconomicDataReducer from "../update_economic_data_reducer";
import UpdateWeatherReducer from "../update_weather_reducer";

export type AddScoreParams = __Infer<typeof AddScoreReducer>;
export type ChangeZoneParams = __Infer<typeof ChangeZoneReducer>;
export type ClearDisasterParams = __Infer<typeof ClearDisasterReducer>;
export type CreateTradeOfferParams = __Infer<typeof CreateTradeOfferReducer>;
export type JoinCityParams = __Infer<typeof JoinCityReducer>;
export type LeaveCityParams = __Infer<typeof LeaveCityReducer>;
export type MoveBuildingParams = __Infer<typeof MoveBuildingReducer>;
export type MoveCursorParams = __Infer<typeof MoveCursorReducer>;
export type PlaceBuildingParams = __Infer<typeof PlaceBuildingReducer>;
export type RemoveBuildingParams = __Infer<typeof RemoveBuildingReducer>;
export type ResetCityParams = __Infer<typeof ResetCityReducer>;
export type RespondToTradeParams = __Infer<typeof RespondToTradeReducer>;
export type TriggerDisasterParams = __Infer<typeof TriggerDisasterReducer>;
export type UndoLastEditParams = __Infer<typeof UndoLastEditReducer>;
export type UpdateCityStatsParams = __Infer<typeof UpdateCityStatsReducer>;
export type UpdateEconomicDataParams = __Infer<typeof UpdateEconomicDataReducer>;
export type UpdateWeatherParams = __Infer<typeof UpdateWeatherReducer>;

